extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: false
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .terraform/
  .git/
  node_modules/
  identity/keycloak/realm-export.json
