[DEFAULT]
bantime  = 24h
findtime = 10m
maxretry = 5
backend  = systemd

[sshd]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 3
bantime  = 24h

[sshd-aggressive]
enabled  = true
port     = ssh
filter   = sshd
mode     = aggressive
maxretry = 10
bantime  = 168h
findtime = 60m
